### ISSUE TITLE
Album Art Fails To Set

### ISSUE THREAD

**Issue by FireController1847** [parshap/node-ffmetadata#20]
Um.. I don't even understand this so...
```
Error: ffmpeg version N-88555-g6ea7711532 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  1.100 / 58.  1.100
  libavformat    58.  0.102 / 58.  0.102
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.101 /  7.  0.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './audio/Tokyo Machine - ROCK IT [Monstercat Release].m4a':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2017-10-11T06:47:49.000000Z
  Duration: 00:03:11.15, start: 0.000000, bitrate: 1508 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1378 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2017-10-11T06:47:49.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 10/10/2017.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2017-10-11T06:47:49.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 10/10/2017.
Input #1, jpeg_pipe, from './temp/thumbnail.jepg':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 320x180 [SAR 1:1 DAR 16:9], 25 tbr, 25 tbn, 25 tbc
[ipod @ 0000018b5092d160] Could not find tag for codec mjpeg in stream #2, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #1:0 -> #0:2 (copy)
    Last message repeated 1 times

    at ChildProcess.<anonymous> (E:\Development\Git\Other\YouTubePlaylistDownloader\node_modules\ffmetadata\index.js:85:16)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5
```

**Comment by FireController1847** [comment]
The file is a .m4a file and I've tried png and jpg

**Comment by parshap** [comment]
## Summary

This is likely due ffmpeg not supporting writing cover art for m4a files. This is reportedly supported now in more recent versions of ffmpeg (see https://github.com/parshap/node-ffmetadata/issues/11#issuecomment-386037697). **If you run into this, try updating ffmpeg.**
