### ISSUE TITLE
Can't find ffmpeg

### ISSUE THREAD

**Issue by MilkLegend** [parshap/node-ffmetadata#23]
module.js:549
    throw err;
    ^

Error: Cannot find module 'Ffmpeg'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\reyna\Desktop\OverRealm Bot\node_modules\prism-media\src\transcoders\MediaTranscoder.js:1:78)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

I have ffmpeg installed and ffmpeg-binaries.

**Comment by parshap** [comment]
I don't see how this is related to the ffmetadata. Looks like [a problem in a really old version of prism-media (?)](https://github.com/hydrabolt/prism-media/blob/0.0.2/src/transcoders/MediaTranscoder.js#L1). Can you provide any more details?

**Comment by MilkLegend** [comment]
Yes that is the coding but since then I started changing the coding trying to find a way if it would work.
